"""fixed Query backref

Revision ID: 4d7ea175f82b
Revises: 798378347a8a
Create Date: 2023-11-27 09:11:34.368710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7ea175f82b'
down_revision: Union[str, None] = '798378347a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genders', ['uuid'])
    op.drop_column('users', 'can_query')
    op.drop_column('users', 'num_queries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('num_queries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_query', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genders', type_='unique')
    # ### end Alembic commands ###
