"""Added the ability to set custom pronounds and descriptions on a day to day basis

Revision ID: 7084389a5547
Revises: 0161d80e4465
Create Date: 2023-11-27 13:05:01.832530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7084389a5547'
down_revision: Union[str, None] = '0161d80e4465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('days', sa.Column('pronouns', postgresql.ARRAY(sa.TEXT()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'pronouns')
    op.drop_column('days', 'description')
    # ### end Alembic commands ###
