"""Initial Migration 3

Revision ID: 798378347a8a
Revises: 525ff5884a37
Create Date: 2023-11-27 08:52:59.178662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '798378347a8a'
down_revision: Union[str, None] = '525ff5884a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('pronouns', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=True),
    sa.Column('ui_settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip', sa.String(length=100), nullable=True),
    sa.Column('last_user_agent', sa.String(length=1000), nullable=True),
    sa.Column('last_country', sa.String(length=1000), nullable=True),
    sa.Column('last_city', sa.String(length=1000), nullable=True),
    sa.Column('last_timezone', sa.String(length=1000), nullable=True),
    sa.Column('num_logins', sa.Integer(), nullable=True),
    sa.Column('num_queries', sa.Integer(), nullable=True),
    sa.Column('can_query', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('days',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('gender_uuid', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['gender_uuid'], ['genders.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid', 'gender_uuid')
    )
    op.create_table('keys',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    op.drop_table('days')
    op.drop_table('users')
    op.drop_table('genders')
    # ### end Alembic commands ###
