"""new UUID for DayTable

Revision ID: 900870146a77
Revises: 7084389a5547
Create Date: 2023-11-27 15:40:31.850346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '900870146a77'
down_revision: Union[str, None] = '7084389a5547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'days', ['uuid'])
    op.drop_column('days', 'pronouns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('pronouns', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'days', type_='unique')
    op.drop_column('days', 'uuid')
    # ### end Alembic commands ###
