"""nameFieldForDay

Revision ID: b0a99e272afd
Revises: 900870146a77
Create Date: 2023-12-02 20:29:38.780570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a99e272afd'
down_revision: Union[str, None] = '900870146a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('name', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('days', 'name')
    # ### end Alembic commands ###
